<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="ThatChat._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.10.2.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Reference to script to update the page and send messages.-->
    <script src="Scripts/fuse.js"></script>

    <!--Our Scripts.-->
    <script src="Scripts/seedrandom-released/seedrandom.min.js"></script>
    <script src="Scripts/OurScripts/SharedVars.js"></script>
    <script src="Scripts/OurScripts/ChatClient.js"></script>
    <script src="Scripts/OurScripts/ConnectionFinished.js"></script>
    <script src="Scripts/OurScripts/Resizing.js"></script>

    <!-- End of script references -->

    <!-- CSS references -->
    <link rel="stylesheet" href="Content/accounts.css">
    <link rel="stylesheet" href="Content/bootstrap.css">
    <link rel="stylesheet" href="Content/site.css">
    <!-- End of CSS references -->

    <!-- Google Font references NOTE: how to use fonts in comment at head of Site.css-->
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <!-- End of Google Font references -->

    <div class="header">
        <h1 class="title">ThatChat</h1>
    </div>
    <div class="container">
        <div class="row" style="height: 100%;">
            <div class="col-md-4">
                <div id="mySideNav" class="sidenav">
                    <a href="javascript:void(0)" id="closebtn" onclick="closeSide()">&times;</a>
                    <div id="sidecontent" class="jumbotron" style="padding: 20px 20px 20px 20px">
                        <h3>&nbsp;Conversations</h3>
                        <div id="search">
                            <input type="text" id="searchBox" class="form-control" placeholder="Search for a chat room" />
                        </div>

                        <ul id="chatRooms" style="list-style: none; padding: 0">
                        </ul>
                        <div id="addchat">
                            <input type="text" id="TextBoxChatAdd" class="inline form-control" placeholder="Add a new chat room" />
                            <input type="button" class="form-control btn-success" id="ButtonChatAdd" value="+">
                        </div>
                        <div id="error" style="display: none;">
                            Invalid chat room name
                        </div>
                    </div>
                </div>
                <div id="header">
                    <span id="burger" onclick="openSide()">&#9776;</span>
                </div>

            </div>

            <div class="col-md-8">
                <div class="jumbotron" id="maincontent">
                    <div id="userInfo">
                        <%--<div id="userID" style="color:white;">awgawgwae</div>--%>
                        <input type="text" id="displayname" class="form-control" />
                        <input type="button" id="setname" class="form-control btn-primary" value="Set Name"/>
                    </div>
                    <hr />
                    <div id="discussionScrollDiv" style="overflow-y: scroll; overflow-wrap: break-word;">
                        <ul id="discussion" style="list-style: none;"></ul>
                    </div>
                    <hr />
                    <div class="messageArea">
                        <div id ="counter" class="counter"></div>
                        <input type="text" id="message" class="form-control" />
                        <input type="button" id="sendmessage" class="form-control btn-success" value="Send" />
                    </div>
                </div>
            </div>
            <input type="button" value="Background: Dynamic" class="btn-primary" id="OnOff" />
        </div>
    </div>

</asp:Content>
